### ISSUE TITLE
Wrong srt is downloaded

### ISSUE THREAD

**Issue by balta2ar** [marhoy/nrk-download#29]
```
nrkdownload -d . 'https://tv.nrk.no/serie/kaass-til-kvelds/2022/MUHU17001022/avspiller'
```
This downloads a subtitle which is ~7.4K in size.
The correct one for this episode is ~40K in size.
After browsing network tab page I found this link for the correct srt: https://undertekst.nrk.no/MUHU17/00/MUHU17001022/TTV/MUHU17001022.vtt
```
nrkdownload version: 3.1.1
```

**Comment by marhoy** [comment]
Thanks for noticing!

Since one of the guests was Swedish, there was two sets of subtitles: One where only the Swedish was translated, and one where everything was texted.

I'm not only downloading the subtitle-file where `defaultOn: True`. The app still does not support programs where the program is too long and therefore split into multiple video- and subtitle-files. If you can find a good example of that, I can have a look at it.

Fixed in PR  #30, merged in version 3.1.2.
